# Generated by Django 4.2.5 on 2023-09-15 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_parent_name_alter_student_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='parent_id',
            field=models.CharField(default=None, editable=False, max_length=6, unique=True),
            preserve_default=False,
        ),
    ]
