# Generated by Django 4.2.5 on 2023-09-19 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_parent_parent_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade_7_8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physics', models.CharField(max_length=4)),
                ('chemistry', models.CharField(max_length=4)),
                ('biology', models.CharField(max_length=4)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.grade_7_8'),
        ),
    ]
