# Generated by Django 4.2.5 on 2023-09-19 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_grade_7_8_alter_student_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='grade',
        ),
    ]
