# Generated by Django 4.2.5 on 2023-09-19 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_student_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.grade_7_8'),
            preserve_default=False,
        ),
    ]
