# Generated by Django 4.2.5 on 2023-09-19 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_remove_student_grade_grade_7_8_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade_7_8',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.student'),
        ),
    ]
