# Generated by Django 4.2.5 on 2023-10-19 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physics', models.CharField(max_length=4)),
                ('chemistry', models.CharField(max_length=4)),
                ('biology', models.CharField(max_length=4)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.CharField(choices=[('5', 'Grade 5'), ('6', 'Grade 6'), ('7', 'Grade 7'), ('8', 'Grade 8'), ('9', 'Grade 9'), ('10', 'Grade 10')], default=None, max_length=2),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.AddField(
            model_name='subject',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.student'),
        ),
    ]
