# Generated by Django 4.2.5 on 2023-10-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_staff_gender_staff_phone_no_student_parent_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='phone_no',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='phone_no',
        ),
        migrations.AddField(
            model_name='parent',
            name='phone',
            field=models.CharField(default='Unknown', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='phone',
            field=models.CharField(default='Unknown', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone',
            field=models.CharField(default='Unknown', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_phone',
            field=models.CharField(default='Unknown', max_length=20, null=True),
        ),
    ]
