# Generated by Django 4.2.5 on 2023-10-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_alter_student_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='parent_phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
