# Generated by Django 4.2.5 on 2023-10-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_remove_teacher_qualifications_remove_teacher_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=None, max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
