# Generated by Django 4.2.5 on 2023-10-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_alter_teacher_experience_alter_teacher_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='parent_to',
            field=models.ManyToManyField(blank=True, null=True, to='base.student'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='phone',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
