# Generated by Django 4.2.5 on 2023-10-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_alter_parent_parent_to_alter_parent_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='parent_to',
            field=models.ManyToManyField(blank=True, to='base.student'),
        ),
    ]
