# Generated by Django 4.2.5 on 2023-10-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_alter_parent_parent_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='parent_to',
        ),
        migrations.AddField(
            model_name='parent',
            name='parent_to',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
