# Generated by Django 4.2.5 on 2023-10-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_remove_parent_parent_to_parent_parent_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='parent_to',
        ),
        migrations.AlterField(
            model_name='staff',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=None, max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.CharField(choices=[('Social Studies', 'Social'), ('Natural Science', 'Natural'), ('Physical Education', 'Sport')], max_length=20),
        ),
    ]
