# Generated by Django 4.2.5 on 2023-10-24 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_student_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('First Semester', '1st'), ('Second Semester', '2nd')], max_length=30)),
                ('physics', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('chemistry', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('biology', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('average', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rank', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.student')),
            ],
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
