# Generated by Django 4.2.5 on 2023-10-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_alter_score_student_alter_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, height_field=300, null=True, upload_to='profile/', width_field=300),
        ),
    ]
