# Generated by Django 4.2.5 on 2023-10-26 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_alter_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, default='user.jpg', null=True, upload_to='profile/'),
        ),
    ]
