# Generated by Django 4.2.5 on 2023-10-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_alter_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
