# Generated by Django 4.2.5 on 2023-11-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_alter_teacher_department_alter_teacher_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='parent_to',
            field=models.ManyToManyField(blank=True, to='base.student'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='experience',
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
    ]
